# Base values for GitHub Actions Runner Scale Set (OCI Chart)
# For use with: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

# GitHub configuration (set via --set in workflow)
githubConfigUrl: ""
githubConfigSecret:
  github_token: ""

# Runner Scale Set name
runnerScaleSetName: "arm64-runners"

# Scaling configuration
minRunners: 0
maxRunners: 5

# Container mode for Docker-in-Docker
containerMode:
  type: "dind"

# ARM64 node selector and container image
template:
  spec:
    nodeSelector:
      kubernetes.io/arch: arm64
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]