# Production environment overrides for OCI Chart
# Only contains differences from base.yaml configuration

# Production runner scale set name
runnerScaleSetName: "production-arm64"

# Higher scaling limits for production
minRunners: 1
maxRunners: 10

# Production template overrides
template:
  spec:
    # ARM64 node selector (from base.yaml)
    nodeSelector:
      kubernetes.io/arch: arm64
      
    # Higher resource limits and production env vars
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
      
      env:
      - name: BUILDX_EXPERIMENTAL
        value: "1"