# GitHub Actions Runner Scale Set Values
# ARC v0.12+ Compatible - NO Docker-in-Docker (for containerd clusters)

githubConfigUrl: https://github.com/wondering-developer
githubConfigSecret:
  github_token: ""  # Will be set via --set

# Runner configuration
runnerGroup: "default"
maxRunners: 5
minRunners: 1

# CRITICAL: This is how runners are targeted now (by installation name)
runnerScaleSetName: "arm64-runners"

# NOTE: runnerLabels are NOT supported in ARC v0.12+
# Runners automatically get: self-hosted, linux, ARM64 based on runtime detection

# Template for ARM64 runners (containerd compatible)
template:
  spec:
    # CRITICAL: This nodeSelector ensures ARM64 placement and triggers ARM64 label
    nodeSelector:
      kubernetes.io/arch: arm64
    
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      
      # Resource configuration
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      
      # Environment variables (NO Docker socket)
      env:
      - name: RUNNER_TOOL_CACHE
        value: "/opt/hostedtoolcache"
      # REMOVED: DOCKER_HOST (causes mount issues)
      
      # Volume mounts (NO Docker socket)
      volumeMounts:
      - name: tool-cache
        mountPath: /opt/hostedtoolcache
    
    # Volumes (NO Docker socket mount)
    volumes:
    - name: tool-cache
      emptyDir: {}
      
    restartPolicy: Never
    
    # Security context
    securityContext:
      runAsUser: 1001
      runAsGroup: 121
      fsGroup: 121

# Autoscaling configuration
scaleDownDelaySecondsAfterScaleOut: 300
scaleDownFactor: 0.5

# Cleanup
podCleanupTimeout: 600
