# GitHub Actions Runner Scale Set Values
# For Organization-Level Runners - Compatible with latest ARC

githubConfigUrl: https://github.com/wondering-developer
githubConfigSecret:
  github_token: ""  # Will be set via --set

# Runner configuration - explicit integer types for template compatibility
runnerGroup: "default"
maxRunners: 5
minRunners: 1

# Runner Scale Set name
runnerScaleSetName: "org-arm64-runners"

# Runner Labels
runnerLabels:
  - "self-hosted"
  - "linux"
  - "ARM64"
  - "arm64-runners"

# Template for ARM64 runners
template:
  spec:
    nodeSelector:
      kubernetes.io/arch: arm64
    
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      
      # Resource configuration for better stability
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      
      # Environment variables
      env:
      - name: RUNNER_TOOL_CACHE
        value: "/opt/hostedtoolcache"
      - name: DOCKER_HOST
        value: "unix:///var/run/docker.sock"
      
      # Volume mounts for Docker-in-Docker
      volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
        readOnly: false
      - name: tool-cache
        mountPath: /opt/hostedtoolcache
    
    # Volumes
    volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: tool-cache
      emptyDir: {}
      
    restartPolicy: Never

# Autoscaling configuration
scaleDownDelaySecondsAfterScaleOut: 300
scaleDownFactor: 0.5

# Cleanup
podCleanupTimeout: 600
