name: Deploy GitHub Actions Runners

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      runner_replicas:
        description: 'Number of runner replicas'
        required: true
        default: '2'
        type: string
      
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/deploy-runners.yml'

env:
  HELM_VERSION: "3.13.0"
  ARC_VERSION: "0.9.3"  # GitHub-unterstützte Version (OCI Registry)

jobs:
  deploy-arc:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          
          # Verify connection
          kubectl cluster-info
          kubectl get nodes

      - name: Install cert-manager (required for ARC)
        run: |
          # Add cert-manager repo
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          
          # Install cert-manager with CRDs
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set crds.enabled=true \
            --set nodeSelector."kubernetes\.io/arch"=arm64 \
            --wait
          
          # Wait for cert-manager to be ready
          kubectl wait --namespace cert-manager \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/name=cert-manager \
            --timeout=300s

      - name: Clean up old repository-level runners
        run: |
          # Remove old repository-level runners
          helm uninstall arm64-runners --namespace actions-runner-system || echo "No old arm64-runners found"
          
          # Wait for cleanup
          sleep 10
          
          # Clean up old resources and remove finalizers if stuck
          kubectl patch autoscalingrunnerset arm64-runners -n actions-runner-system \
            --type=merge -p '{"metadata":{"finalizers":null}}' || echo "No old AutoscalingRunnerSet found"
          
          kubectl delete autoscalingrunnerset arm64-runners -n actions-runner-system || echo "No old AutoscalingRunnerSet found"

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Install ARC Controller (OCI Registry)
        run: |
          helm upgrade --install arc \
            --namespace actions-runner-system \
            --create-namespace \
            --set nodeSelector."kubernetes\.io/arch"=arm64 \
            --wait \
            oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

      - name: Deploy Runner Scale Set (Organization-Level)
        run: |
          # Organization-level runners for all repositories
          helm upgrade --install org-arm64-runners \
            --namespace actions-runner-system \
            --create-namespace \
            --set githubConfigUrl="https://github.com/wondering-developer" \
            --set githubConfigSecret.github_token="${{ secrets.TOKEN }}" \
            --set maxRunners="${{ github.event.inputs.runner_replicas || '5' }}" \
            --set minRunners="1" \
            --set runnerGroup="default" \
            --set runnerLabels[0]="self-hosted" \
            --set runnerLabels[1]="linux" \
            --set runnerLabels[2]="ARM64" \
            --set runnerLabels[3]="arm64-runners" \
            --set template.spec.nodeSelector."kubernetes\.io/arch"=arm64 \
            --wait \
            oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set

      - name: Verify deployment
        run: |
          echo "Checking ARC Controller status..."
          kubectl get pods -n actions-runner-system
          
          echo "Checking AutoscalingRunnerSet (new ARC API)..."
          kubectl get autoscalingrunnerset -n actions-runner-system || echo "No AutoscalingRunnerSet found"
          
          echo "Checking EphemeralRunnerSet..."
          kubectl get ephemeralrunnerset -n actions-runner-system || echo "No EphemeralRunnerSet found"
          
          echo "Checking all custom resources..."
          kubectl api-resources | grep actions || echo "ARC CRDs not found"
          
          echo "Checking events for any issues..."
          kubectl get events -n actions-runner-system --sort-by='.lastTimestamp' | tail -10

      - name: Run setup verification
        run: |
          chmod +x ./scripts/verify-setup.sh
          ./scripts/verify-setup.sh
